In [ ]:
"""
Sometimes you want to create a matrix without typing out all of the entries.

I can see this being popular with identity matrix and the zero vector.

Let's see a few options that are made available by numpy
"""

In [1]:
import numpy as np

In [2]:
# Create a matrix composed of 0's
Z = np.zeros((3,3))
print(Z)
# Note: That the argument is type (r,c) !== r,c

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [3]:
# Create a matrix composed of all 1's
Ones = np.ones((3,3))
print(Ones)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [4]:
# Create an array that is composed of a constant in each entry
# Arguments are ((r,c), constant)
Constant_Entry_Matrix = np.full((2,2), 5)
print(Constant_Entry_Matrix)

[[5 5]
 [5 5]]


In [5]:
# I would imagine that being able to print the identity matrix would be important
# It creates a In of the size n passed as the argument to np.eye(n) 
# n=number of rows & number of columns (square of course)
identity = np.eye(5)
print(identity)

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [6]:
# If I want to generate a random matrix I can do that by
random_matrix = np.random.random((3,3))
print(random_matrix)

[[ 0.35995355  0.57521423  0.73195201]
 [ 0.57610197  0.37581339  0.2902875 ]
 [ 0.47854104  0.30425586  0.81913009]]
