In [2]:
import numpy as np

In [3]:
M = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(M)
print(M.shape)
# "Matrix M is a Matrix of Size 3x3: 3 rows by 3 Columns"

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [4]:
v = np.array([
            [1],
            [2],
            [3]
])
print(v)
print(v.shape)
# "Vector v is a vector of size 3x1: 3rows by 1 column

[[1]
 [2]
 [3]]
(3, 1)


In [5]:
u_single_dimension = np.array([1, 2, 3])
print(u_single_dimension)
print(u_single_dimension.shape)
# This is interesting - What does this mean? This is something I will look into...

[1 2 3]
(3,)


In [6]:
# Vector Addition is done entrywise:
# Let's see if it is calculated properly in numpy
print(v + v)
# Success! It was done Entrywise

[[2]
 [4]
 [6]]
