In [1]:
"""

"""

import numpy as np
D = np.array([[0.0112, 0.0045, 0.0022], [0.0045, 0.0089, 0.0045], [0.0022, 0.0045, 0.0112]])
print(np.linalg.inv(D))

[[ 112.05631736  -57.13560183    0.94520625]
 [ -57.13560183  170.13712544  -57.13560183]
 [   0.94520625  -57.13560183  112.05631736]]
